### PR TITLE
Initial implementation of a BroadcastChannel polyfill

### LINKED ISSUE #15: Created a idb-based polyfill for MessageBus

### PR DESCRIPTION
**Pull request by TimvdLippe**
My condolences if you are reading this code.

Closes #15

### CODE REVIEW

**Comment by hkfrei** [comment]
Would be cool if a BroadcastChannel polyfill could be implemented. I like your [actor model example](https://github.com/PolymerLabs/actor-boilerplate) very much and with a polyfill it would run in every browser.

**Comment by surma** [comment]
For the record: `actor-boilerplate` does run in every browser! 

We just opted out of calling it “polyfilling `BroadcastChannel`” as we would have to replicate all the behavior of BroadcastChannel, even though we only need a specific subset. Especially when you throw ServiceWorker into the mix, things get messy.

We chose a different route to make `actor-boilerplate` work, but we’d love to see Safari and Edge ship BCC, as it would make the library considerably more lightweight.

**Comment by hkfrei** [comment]
Well, my experience is, that the counter does not increment/decrement in Safari or Edge. Chrome and Firefox work great (I use a MacBook Pro).

Steps to reproduce:
`git clone git@github.com:PolymerLabs/actor-boilerplate.git`
`cd actor-boilerplate`
`npm install`
`npm run build`
`npm run serve`

Then visit http://localhost:8080 in Safari or Edge and clicking the buttons, does not update the counter.

I' didn't dive deep in the code but [here](https://github.com/PolymerLabs/actor-helpers/blob/0c61eb2047845b7447712cca8adf8dd8b481a6b0/src/watchable-message-store/WatchableMessageStore.ts#L166) you check if bcc is available. In my case (on Safari/Edge) bcc is undefined and therefore no message is pushed.
Also [here](https://github.com/PolymerLabs/actor-helpers/blob/0c61eb2047845b7447712cca8adf8dd8b481a6b0/src/watchable-message-store/WatchableMessageStore.ts#L68) no bcc is assigned when if statements evaluates to false?

**Comment by surma** [comment]
Yeah, we use BCC when it’s available, otherwise we fall back to polling.

You are right tho, the demo doesn’t work. Or rather, it only works for about 2 seconds 😂 

We found that Safari kills workers quite quickly if you don’t use `postMessage()` (which we don’t). We figured this out a while ago but apparently didn’t update the demo code. I’ll push a commit in a second.

**Comment by hkfrei** [comment]
Great, thank you.

**Comment by surma** [comment]
@hkfrei Fixed on master and I tested in Safari stable locally. Please open a new issue if it’s still not working :)

**Comment by surma** [comment]
Fixed on master of `actor-boilerplate`, that is.

**Comment by hkfrei** [comment]
Works like a charm ;-)

**Comment by surma** [comment]
_phew_

**Pull request closed without merging**
